version: '3'

  api:
    image: dokazovi
    container_name: dokazovi
    ports:
      - '8080:8080'
    env_file:
      - .env/dokazovi.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
